<?php
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\AtlasDetailController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\Admin\ArticleController as AdminArticleController;
use App\Http\Controllers\Admin\AtlasController as AdminAtlasController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\TagController as AdminTagController;
use App\Http\Controllers\Admin\VideoController as AdminVideoController;
use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;

Route::get('/login', [LoginController::class, 'create'])->name('login');
Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', AdminDashboardController::class)->name('index');
    Route::patch('/articles/{article}/publish', [AdminArticleController::class, 'togglePublish'])->name('articles.publish');
    Route::resource('articles', AdminArticleController::class)->except(['show', 'destroy']);
    Route::patch('/videos/{video}/publish', [AdminVideoController::class, 'togglePublish'])->name('videos.publish');
    Route::resource('videos', AdminVideoController::class)->except(['show', 'destroy']);
    Route::resource('categories', AdminCategoryController::class)->only(['index', 'store']);
    Route::resource('tags', AdminTagController::class)->only(['index', 'store']);
    Route::get('/atlas/{resource}', [AdminAtlasController::class, 'index'])->name('atlas.index');
    Route::get('/atlas/{resource}/create', [AdminAtlasController::class, 'create'])->name('atlas.create');
    Route::post('/atlas/{resource}', [AdminAtlasController::class, 'store'])->name('atlas.store');
    Route::get('/atlas/{resource}/{id}/edit', [AdminAtlasController::class, 'edit'])->name('atlas.edit');
    Route::put('/atlas/{resource}/{id}', [AdminAtlasController::class, 'update'])->name('atlas.update');
    Route::delete('/atlas/{resource}/{id}', [AdminAtlasController::class, 'destroy'])->name('atlas.destroy');
});
Route::get('/', [PageController::class,'home'])->name('home');
Route::get('/about', [PageController::class,'about'])->name('about');
Route::get('/services', [PageController::class,'services'])->name('services');
Route::get('/articles', [ArticleController::class,'index'])->name('articles.index');
Route::get('/articles/{article:slug}', [ArticleController::class,'show'])->name('articles.show');
Route::get('/videos', [PageController::class,'videos'])->name('videos');
Route::get('/tools', [PageController::class,'tools'])->name('tools');
Route::get('/opportunity-atlas', [PageController::class,'atlas'])->name('atlas');
Route::get('/opportunity-atlas/industries/{industry:slug}', [AtlasDetailController::class, 'industry'])->name('atlas.industries.show');
Route::get('/opportunity-atlas/company-types/{companyType:slug}', [AtlasDetailController::class, 'companyType'])->name('atlas.company-types.show');
Route::get('/opportunity-atlas/departments/{department:slug}', [AtlasDetailController::class, 'department'])->name('atlas.departments.show');
Route::get('/opportunity-atlas/workflows/{workflow:slug}', [AtlasDetailController::class, 'workflow'])->name('atlas.workflows.show');
Route::get('/opportunity-atlas/friction-points/{frictionPoint:slug}', [AtlasDetailController::class, 'frictionPoint'])->name('atlas.friction-points.show');
Route::get('/opportunity-atlas/solution-patterns/{solutionPattern:slug}', [AtlasDetailController::class, 'solutionPattern'])->name('atlas.solution-patterns.show');
Route::get('/opportunity-atlas/capabilities/{capability:slug}', [AtlasDetailController::class, 'capability'])->name('atlas.capabilities.show');
Route::get('/contact', [PageController::class,'contact'])->name('contact');
Route::post('/contact', [PageController::class,'submitContact'])->name('contact.submit');
Route::get('/ai-readiness-assessment', [PageController::class,'assessment'])->name('assessment');
Route::post('/ai-readiness-assessment', [PageController::class,'submitAssessment'])->name('assessment.submit');
Route::get('/ai-readiness-assessment/{assessment}', [PageController::class,'assessmentResult'])->name('assessment.result');