<?php

return [
    'items' => [
        [
            'title' => 'Inventory Synchronization Laboratory',
            'slug' => 'inventory-synchronization-laboratory',
            'description' => 'An executable engineering textbook for learning inventory synchronization and distributed-systems correctness through deterministic Python models.',
            'domain' => 'Distributed systems',
            'repository_url' => 'https://github.com/Garcia-Systems/inventory-synchronization-laboratory',
            'status' => 'Educational laboratory',
            'technologies' => ['Python', 'CLI', 'Automated tests'],
            'key_concepts' => ['Idempotency', 'Retries', 'Ordering', 'Projections'],
            'architecture' => ['Ledger', 'Sync request', 'Queue', 'Workers', 'Projections'],
            'featured' => true,
        ],
        [
            'title' => 'Executable Digital Banking Integration Laboratory',
            'slug' => 'executable-digital-banking-integration-laboratory',
            'description' => 'A deterministic full-stack laboratory for learning how to extend a vendor-centered digital banking ecosystem safely.',
            'domain' => 'Digital banking integration',
            'repository_url' => 'https://github.com/Garcia-Systems/executable-digital-banking-integration-laboratory',
            'status' => 'Educational laboratory',
            'technologies' => ['Full stack', 'REST', 'SOAP', 'SQL'],
            'key_concepts' => ['System boundaries', 'Adapters', 'Verification', 'Fintech integration'],
            'architecture' => ['Member experience', 'Harbor API', 'Application services', 'Vendor REST', 'Legacy SOAP', 'SQL', 'Verification / fintech'],
            'featured' => true,
        ],
        [
            'title' => 'Executable Regional Economy Laboratory',
            'slug' => 'executable-regional-economy-laboratory',
            'description' => 'A deterministic, inspectable model for learning how selected money, capacity, and service flows move through a fictional regional economy.',
            'domain' => 'Regional economics',
            'repository_url' => 'https://github.com/Garcia-Systems/executable-regional-economy-laboratory',
            'status' => 'Educational laboratory',
            'technologies' => ['Deterministic simulation', 'CLI', 'Tests'],
            'key_concepts' => ['Flows', 'Capacity', 'Constraints', 'Ending positions'],
            'architecture' => ['Inputs', 'Participants', 'Transactions', 'Constraints', 'Outflows', 'Ending positions'],
            'featured' => true,
        ],
        [
            'title' => 'Executable Sales Engineering Laboratory',
            'slug' => 'executable-sales-engineering-laboratory',
            'description' => 'An executable textbook that makes technical discovery, requirements, solution design, risk, value, and recommendation reasoning inspectable.',
            'domain' => 'Sales engineering',
            'repository_url' => 'https://github.com/Garcia-Systems/executable-sales-engineering-laboratory',
            'status' => 'Educational laboratory',
            'technologies' => ['Executable textbook', 'Scenarios', 'Tests'],
            'key_concepts' => ['Discovery', 'Requirements', 'Risk', 'Evidence'],
            'architecture' => ['Customer context', 'Discovery', 'Requirements', 'Solution', 'Evidence', 'Recommendation'],
            'featured' => true,
        ],
    ],
];
