<form method="POST" action="{{ $action }}" class="space-y-5 rounded-xl border border-white/10 bg-white/5 p-6">@csrf @if($method !== 'POST') @method($method) @endif
<div><label class="block text-sm font-semibold">Name</label><input class="mt-1 w-full rounded bg-slate-950 p-3" name="name" value="{{ old('name', $item->name) }}" required></div><div><label class="block text-sm font-semibold">Slug</label><input class="mt-1 w-full rounded bg-slate-950 p-3" name="slug" value="{{ old('slug', $item->slug) }}" placeholder="Generated from name when blank"></div>
@if(isset($config['parents']['industry_id']))<div><label class="block text-sm font-semibold">Industry</label><select class="mt-1 w-full rounded bg-slate-950 p-3" name="industry_id" required>@foreach($options['industries'] as $parent)<option value="{{ $parent->id }}" @selected(old('industry_id', $item->industry_id) == $parent->id)>{{ $parent->name }}</option>@endforeach</select></div>@endif
@if(isset($config['parents']['company_type_id']))<div><label class="block text-sm font-semibold">Company Type</label><select class="mt-1 w-full rounded bg-slate-950 p-3" name="company_type_id" required>@foreach($options['companyTypes'] as $parent)<option value="{{ $parent->id }}" @selected(old('company_type_id', $item->company_type_id) == $parent->id)>{{ $parent->name }}</option>@endforeach</select></div>@endif
@if(isset($config['parents']['department_id']))<div><label class="block text-sm font-semibold">Department</label><select class="mt-1 w-full rounded bg-slate-950 p-3" name="department_id" required>@foreach($options['departments'] as $parent)<option value="{{ $parent->id }}" @selected(old('department_id', $item->department_id) == $parent->id)>{{ $parent->name }}</option>@endforeach</select></div>@endif
@if(isset($config['parents']['workflow_id']))<div><label class="block text-sm font-semibold">Workflow</label><select class="mt-1 w-full rounded bg-slate-950 p-3" name="workflow_id" required>@foreach($options['workflows'] as $parent)<option value="{{ $parent->id }}" @selected(old('workflow_id', $item->workflow_id) == $parent->id)>{{ $parent->name }}</option>@endforeach</select></div>@endif
@if($resource === 'friction-points')<div><label class="block text-sm font-semibold">Impact</label><input class="mt-1 w-full rounded bg-slate-950 p-3" name="impact" value="{{ old('impact', $item->impact) }}"></div><div><label class="block text-sm font-semibold">Solution Patterns</label><select multiple class="mt-1 w-full rounded bg-slate-950 p-3" name="solution_pattern_ids[]">@foreach($options['solutionPatterns'] as $option)<option value="{{ $option->id }}" @selected(collect(old('solution_pattern_ids', $item->solutionPatterns?->pluck('id')->all() ?? []))->contains($option->id))>{{ $option->name }}</option>@endforeach</select></div>@endif
@if($resource === 'solution-patterns')<div><label class="block text-sm font-semibold">Capabilities</label><select multiple class="mt-1 w-full rounded bg-slate-950 p-3" name="capability_ids[]">@foreach($options['capabilities'] as $option)<option value="{{ $option->id }}" @selected(collect(old('capability_ids', $item->capabilities?->pluck('id')->all() ?? []))->contains($option->id))>{{ $option->name }}</option>@endforeach</select></div>@endif
<div><label class="block text-sm font-semibold">Description</label><textarea class="mt-1 w-full rounded bg-slate-950 p-3" name="description" rows="5">{{ old('description', $item->description) }}</textarea></div><button class="rounded bg-cyan-400 px-4 py-2 font-semibold text-slate-950">Save {{ $config['singular'] }}</button></form>
