<x-admin.layout heading="Leads">
    <form method="get" action="{{ route('admin.leads.index') }}" class="mb-6 grid gap-3 rounded-xl border border-slate-700 bg-slate-900 p-4 md:grid-cols-4">
        <input class="rounded px-3 py-2 text-slate-900" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Search name, email, company">
        <select class="rounded px-3 py-2 text-slate-900" name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ str($status)->headline() }}</option>@endforeach</select>
        <select class="rounded px-3 py-2 text-slate-900" name="source"><option value="">All sources</option>@foreach($sources as $source)<option value="{{ $source }}" @selected(($filters['source'] ?? '') === $source)>{{ str($source)->replace('_', ' ')->headline() }}</option>@endforeach</select>
        <button class="rounded border border-slate-600 px-4 py-2">Filter leads</button>
    </form>
    <div class="overflow-hidden rounded-xl border border-slate-700"><table class="w-full text-left text-sm"><thead class="bg-slate-900 text-slate-200"><tr><th class="p-3">Name</th><th class="p-3">Email</th><th class="p-3">Company</th><th class="p-3">Source</th><th class="p-3">Status</th><th class="p-3">Assessment</th><th class="p-3">Created</th><th class="p-3">Latest activity</th></tr></thead><tbody class="divide-y divide-slate-700">@forelse($leads as $lead)<tr><td class="p-3"><a class="font-semibold text-cyan-300" href="{{ route('admin.leads.show', $lead) }}">{{ $lead->name ?: 'Unnamed lead' }}</a></td><td class="p-3">{{ $lead->email }}</td><td class="p-3">{{ $lead->company ?: '—' }}</td><td class="p-3">{{ str($lead->source)->replace('_', ' ')->headline() }}</td><td class="p-3">{{ str($lead->status)->headline() }}</td><td class="p-3">@if($lead->assessment_score !== null){{ $lead->assessment_score }} · {{ $lead->assessment_tier }}@else — @endif</td><td class="p-3">{{ $lead->created_at?->format('M j, Y') }}</td><td class="p-3">{{ $lead->latest_activity_at?->format('M j, Y') ?: '—' }}</td></tr>@empty<tr><td class="p-3 text-slate-400" colspan="8">No leads yet.</td></tr>@endforelse</tbody></table></div><div class="mt-6">{{ $leads->links() }}</div>
</x-admin.layout>
