<x-layouts.app title="Services" page-description="Systems analysis, executable modeling, software integration, workflow modernization, AI enablement, and technical solutions engineering grounded in reproducible evidence.">
    @php
        $services = [
            ['label'=>'Understand','title'=>'Systems Analysis & Discovery','overview'=>'Understand workflows, actors, information, constraints, friction, and technical boundaries before selecting a solution.','problems'=>'Ambiguous requirements, disconnected stakeholders, hidden dependencies, unclear ownership, and technology decisions made before the work is understood.','outcomes'=>'An explicit system boundary, shared problem definition, mapped information flow, and evidence-based options for the next decision.','deliverables'=>['System and workflow maps','Stakeholder and actor maps','Constraint and dependency notes','Opportunity maps','Prioritized requirements'],'clients'=>'Teams facing a real operational problem that need clarity before committing to software, automation, or organizational change.','examples'=>['Map an intake workflow and its handoffs before choosing an automation platform.','Expose system boundaries and data ownership before planning an integration.'],'cta'=>'Understand a system'],
            ['label'=>'Improve','title'=>'Software & Integration Engineering','overview'=>'Design and build focused applications, APIs, adapters, workflows, and integrations that connect real operational systems.','problems'=>'Disconnected tools, brittle data movement, vendor gaps, manual reconciliation, and important work split across incompatible interfaces.','outcomes'=>'A practical engineering path with explicit interfaces, failure behavior, implementation priorities, and verification criteria.','deliverables'=>['Application and API design','Integration plans','Adapter specifications','Prototypes','Automated test strategies','Implementation roadmaps'],'clients'=>'Organizations that need focused software or integration engineering rather than unnecessary platform complexity.','examples'=>['Design an adapter around vendor and legacy service boundaries.','Replace manual data transfer with a testable integration workflow.'],'cta'=>'Discuss an integration'],
            ['label'=>'Model','title'=>'Executable Modeling & Simulation','overview'=>'Turn complicated processes, architectures, policies, and technical concepts into deterministic models that teams can inspect, run, test, and change.','problems'=>'Important decisions resting on diagrams alone, implicit assumptions, behavior that is hard to explain, or concepts that cannot be tested safely in a live system.','outcomes'=>'A reproducible learning environment where scenarios, boundaries, assumptions, and claims can be examined directly.','deliverables'=>['Deterministic simulations','Executable textbooks','Controlled scenarios','System diagrams','Command-line demonstrations','Automated tests'],'clients'=>'Technical and cross-functional teams that need to learn, communicate, or test system behavior without claiming a model is a production architecture.','examples'=>['Model synchronization retries and projections deterministically.','Make a policy or transaction flow inspectable through controlled scenarios.'],'cta'=>'Explore executable modeling'],
            ['label'=>'Improve','title'=>'Workflow Automation & AI Enablement','overview'=>'Introduce automation or AI only where workflow quality, data, ownership, governance, and measurable value support it.','problems'=>'Pressure to adopt AI without a use case, unstable workflows, weak data ownership, unclear risk tolerance, and pilots disconnected from outcomes.','outcomes'=>'A readiness profile, prioritized opportunity, explicit risks, and a controlled pilot or modernization path with success criteria.','deliverables'=>['Workflow readiness review','Data dependency notes','Risk and governance notes','Automation options','Pilot scenarios','Measurement plan'],'clients'=>'Leaders and operators seeking grounded automation or AI decisions rather than technology-led experimentation.','examples'=>['Assess a document workflow before adding AI assistance.','Define ownership and evidence needed for a controlled decision-support pilot.'],'cta'=>'Assess readiness'],
            ['label'=>'Translate','title'=>'Technical Translation & Solutions Engineering','overview'=>'Connect business needs, technical architecture, vendors, leadership, and implementation teams through shared models and explicit decisions.','problems'=>'Misaligned vocabulary, unclear tradeoffs, vendor ambiguity, incomplete acceptance criteria, and solutions drifting from operational intent.','outcomes'=>'Better decision quality, testable requirements, clearer interfaces, documented tradeoffs, and verification criteria everyone can use.','deliverables'=>['Requirements and decision records','Solution designs','Vendor evaluations','Acceptance criteria','Risk registers','Verification plans'],'clients'=>'Organizations that need a reliable translation layer between business and technical participants.','examples'=>['Turn discovery evidence into testable solution requirements.','Frame vendor tradeoffs around system boundaries, risk, and observable outcomes.'],'cta'=>'Align the system'],
        ];
    @endphp
    <section class="gs-shell gs-section">
        <p class="gs-eyebrow">Services</p>
        <h1 class="mt-4 max-w-5xl text-4xl font-bold tracking-tight md:text-6xl">Improve systems from evidence, not technology hype.</h1>
        <p class="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Garcia Systems combines systems analysis, executable modeling, software engineering, integration, and technical translation. Engagements begin by understanding the operating system and end with explicit ways to verify improvement.</p>
    </section>
    <section class="gs-shell pb-12">
        <x-section-heading eyebrow="Capabilities" title="Five connected ways to understand, model, improve, and verify." description="The laboratories demonstrate the method; service work applies it to practical decisions and delivery." />
        <div class="mt-8 grid gap-7">@foreach($services as $service)<x-service-card :service="$service" />@endforeach</div>
    </section>
    <x-cta-banner title="Bring the system, not a predetermined tool." description="Start with the actors, information, workflow, constraints, and outcome that matter." :href="route('contact')" linkText="Start a conversation" />
</x-layouts.app>
